name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:


      - uses: actions/checkout@v1
      
      
      - name: Build the Docker image
        working-directory: .
        run: docker build . --file Dockerfile --tag my-app-flask:latest
        
        
      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}
          repository: raintrains/git_actions
          tags: latest, ${{ github.run_number }}
