name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:


      - uses: actions/checkout@v1
      
      
      - name: Build the Docker image
        working-directory: .
        run: docker build . --file Dockerfile --tag my-app-flask:latest
        
        