name: Docker Image CI

on:
  push:
    branches: [ "main" ]


jobs:

  build:

    runs-on: ubuntu-latest

    steps:
        - name: Login to DockerHub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASS }}
    
        - name: Build and push docker image
          run: |
            docker build -t raintrains/devops/flask_app:latest -f raintrains/DevOps/
            docker push raintrains/devops/flask_app:latest